services:
  nodo1:
    build: .
    container_name: nodo1
    command: python distributed_fs.py --id 1 --port 50051 --peers nodo2:50052,nodo3:50053,nodo4:50054 --root /data --op wait
    volumes:
      - ./nodo1:/data
    networks:
      - redfs

  nodo2:
    build: .
    container_name: nodo2
    command: python distributed_fs.py --id 2 --port 50052 --peers nodo1:50051,nodo3:50053,nodo4:50054 --root /data --op wait
    volumes:
      - ./nodo2:/data
    networks:
      - redfs

  nodo3:
    build: .
    container_name: nodo3
    command: python distributed_fs.py --id 3 --port 50053 --peers nodo1:50051,nodo2:50052,nodo4:50054 --root /data --op wait
    volumes:
      - ./nodo3:/data
    networks:
      - redfs

  nodo4:
    build: .
    container_name: nodo4
    command: python distributed_fs.py --id 4 --port 50054 --peers nodo1:50051,nodo2:50052,nodo3:50053 --root /data --op wait
    volumes:
      - ./nodo4:/data
    networks:
      - redfs

networks:
  redfs:
    driver: bridge